spring:
  datasource:
    initialize: true
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/?currentSchema=mydb
    username: postgres
    password: postgres

  jpa:
#    database: POSTGRESQL
#    database-platform: com.example.jpa.config.MyDialect
    show-sql: true
    properties:
      org:
        hibernate:
          flushMode: ALWAYS

#        dialect: org.hibernate.dialect.PostgreSQL9Dialect

# logging:
#    level:
#      ROOT: DEBUG