spring:
  datasource:
    initialize: true
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/?currentSchema=mydb
    username: postgres
    password: postgres

  jpa:
    show-sql: true
    properties:
      org:
        hibernate:
          flushMode: ALWAYS

# logging:
#    level:
#      ROOT: DEBUG